<?php
/**
 * Created by PhpStorm.
 * User: Daniellz
 * Date: 14.08.2018
 * Time: 13:28
 */

namespace app\widgets\stars;


use yii\web\AssetBundle;

class StarsAssets extends AssetBundle
{
    public $sourcePath = '@app/assets/starsrating';
    public $css = [
        //                'usercard.less',
    ];
    public $js = [
        'stars.js'
        //        'js/jquery.inputmask.bundle.min.js',
        //        'js/phones.js',
        //        'js/pincode.js',
        //        'js/reg.js',
    ];
    public $depends = [
        //        'yii\web\YiiAsset',
        //        'yii\bootstrap\BootstrapAsset',
    ];
    public function publish($am)
    {
        //        $am->forceCopy = true;
        $am->appendTimestamp = true;
        //        $am->linkAssets = false;
        parent::publish($am); // TODO: Change the autogenerated stub
    }
}