<?php
/**
 * Created by PhpStorm.
 * User: Daniellz
 * Date: 11.07.2018
 * Time: 14:39
 */

namespace app\assets;


use yii\web\AssetBundle;

class TurnJsAsset extends AssetBundle
{
//    public $basePath = '@webroot';
//    public $baseUrl = '@web';
    public $sourcePath = '@app/assets/app';
    public $css = [
        'less/brandbook.less',
    ];
    public $js = [
        'js/turn.js',
        'js/brandbook.js',
    ];
    public $depends = [
        'yii\web\JqueryAsset'
//        'yii\bootstrap\BootstrapAsset',
    ];
    public function publish($am)
    {
        $am->appendTimestamp = true;
        $am->linkAssets = true;
        parent::publish($am); // TODO: Change the autogenerated stub
    }
}