<?php
/**
 * Created by PhpStorm.
 * User: Daniellz
 * Date: 09.10.2018
 * Time: 16:34
 */

namespace app\assets\app;


use app\assets\AppAsset;
use yii\web\AssetBundle;

class PhoneInputAsset extends AssetBundle
{
    public $sourcePath = '@app/assets/login';
    public $css = [
    ];
    public $js = [
        'js/jquery.inputmask.bundle.min.js',
        'js/phones.js',
        'js/pincode.js',
    ];
    public $depends = [
        AppAsset::class,
    ];
    public function publish($am)
    {
        $am->forceCopy = true;
        $am->appendTimestamp = true;
        $am->linkAssets = false;
        parent::publish($am); // TODO: Change the autogenerated stub
    }
}